[package]
name = "kdsfarm"
version = "0.1.0"
authors = ["Solarys <strafe.solarys@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp3-duration = "0.1.10"